"""empty message

Revision ID: 4475e32cf552
Revises: ee577ad3a3be
Create Date: 2018-10-23 14:23:19.129873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4475e32cf552'
down_revision = 'ee577ad3a3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mit_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=120), nullable=True),
    sa.Column('exec_mode', sa.String(length=120), nullable=True),
    sa.Column('apply_to_device', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mit_commands_command'), 'mit_commands', ['command'], unique=False)
    op.create_table('mit_devicetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_model', sa.String(length=120), nullable=True),
    sa.Column('device_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mit_devicetype_device_class'), 'mit_devicetype', ['device_class'], unique=False)
    op.create_index(op.f('ix_mit_devicetype_device_model'), 'mit_devicetype', ['device_model'], unique=False)
    op.create_table('mit_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mit_users_username'), 'mit_users', ['username'], unique=False)
    op.drop_index('ix_device_type_device_class', table_name='device_type')
    op.drop_index('ix_device_type_device_model', table_name='device_type')
    op.drop_table('device_type')
    op.drop_index('ix_command_command', table_name='command')
    op.drop_table('command')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_type', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_table('command',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('command', sa.VARCHAR(length=120), nullable=True),
    sa.Column('exec_mode', sa.VARCHAR(length=120), nullable=True),
    sa.Column('apply_to_device', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_command_command', 'command', ['command'], unique=False)
    op.create_table('device_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_class', sa.VARCHAR(length=120), nullable=True),
    sa.Column('device_model', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_type_device_model', 'device_type', ['device_model'], unique=False)
    op.create_index('ix_device_type_device_class', 'device_type', ['device_class'], unique=False)
    op.drop_index(op.f('ix_mit_users_username'), table_name='mit_users')
    op.drop_table('mit_users')
    op.drop_index(op.f('ix_mit_devicetype_device_model'), table_name='mit_devicetype')
    op.drop_index(op.f('ix_mit_devicetype_device_class'), table_name='mit_devicetype')
    op.drop_table('mit_devicetype')
    op.drop_index(op.f('ix_mit_commands_command'), table_name='mit_commands')
    op.drop_table('mit_commands')
    # ### end Alembic commands ###
