"""empty message

Revision ID: ee577ad3a3be
Revises: 
Create Date: 2018-10-17 21:08:14.513725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee577ad3a3be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=120), nullable=True),
    sa.Column('exec_mode', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_command'), 'command', ['command'], unique=False)
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_type_device_name'), 'device_type', ['device_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_device_type_device_name'), table_name='device_type')
    op.drop_table('device_type')
    op.drop_index(op.f('ix_command_command'), table_name='command')
    op.drop_table('command')
    # ### end Alembic commands ###
